# Generated by Django 5.1.4 on 2024-12-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='file',
        ),
    ]
