# Generated by Django 5.1.4 on 2024-12-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_remove_paper_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='temp_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/'),
        ),
    ]
