# Generated by Django 5.1.4 on 2024-12-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_temp_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='ipfs_hash',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
