# Generated by Django 5.1.4 on 2024-12-25 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_alter_paper_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='user',
        ),
        migrations.AddField(
            model_name='paper',
            name='user_uid',
            field=models.CharField(default=datetime.date(2024, 12, 27), max_length=255),
            preserve_default=False,
        ),
    ]
