# Generated by Django 5.1.4 on 2024-12-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0008_alter_paper_ipfs_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='location',
        ),
        migrations.AddField(
            model_name='paper',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='ipfs_hash',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='user_uid',
            field=models.CharField(max_length=100),
        ),
    ]
