# Generated by Django 5.1.4 on 2024-12-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_remove_paper_location_paper_transaction_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='transaction_hash',
        ),
        migrations.AlterField(
            model_name='paper',
            name='ipfs_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='temp_file',
            field=models.FileField(null=True, upload_to='temp/'),
        ),
    ]
