# Generated by Django 5.1.4 on 2024-12-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0011_paper_city_paper_coordinates_paper_land_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='city',
            field=models.CharField(help_text='Enter the city name.', max_length=200),
        ),
    ]
